Repository jimp-dev/jimp, pull requests merged in 2018-09, with the labels that each got.

#584 Double Callback
  packages/core/src/utils/image-bitmap.js
Labels: bug

#591 update utif and fix dep problem
  packages/type-tiff/package.json
  yarn.lock
Labels: bug

#587 Convolution Bug
  packages/jimp/test/convolution.test.js
  packages/jimp/test/samples/qr-convoluted.png
  packages/jimp/test/samples/qr.jpg
  packages/plugin-color/src/index.js
Labels: bug

#585 Has alpha
  README.md
  packages/core/src/index.js
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/jimp/test/filetypes.test.js
Labels: enhancement

#588 Print number
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/jimp/test/print.test.js
  packages/jimp/test/samples/text-samples/print-number.png
  packages/plugin-print/src/index.js
Labels: enhancement

#586 Distance from hash
  packages/core/src/index.js
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/jimp/test/hash.test.js
Labels: enhancement

#594 Circle plugin
  README.md
  packages/plugin-circle/LICENSE
  packages/plugin-circle/README.md
  packages/plugin-circle/babel.config.js
  packages/plugin-circle/package.json
  packages/plugin-circle/src/index.js
  packages/plugin-circle/test.png
  packages/plugin-circle/test/circle.test.js
  packages/plugin-circle/test/images/circled.png
  packages/plugin-circle/test/images/radius-3-circle.png
  packages/plugin-circle/test/images/x-y-circle.png
Labels: internal

#598 Document re - configure jimp
  packages/custom/README.md
Labels: internal

#352 Threshold Plugin
  README.md
  packages/plugin-threshold/LICENSE
  packages/plugin-threshold/README.md
  packages/plugin-threshold/babel.config.js
  packages/plugin-threshold/package.json
  packages/plugin-threshold/src/index.js
  packages/plugin-threshold/test/images/hands.jpg
  packages/plugin-threshold/test/images/hands_mx200_rp255.jpg
  packages/plugin-threshold/test/threshold.test.js
Labels: internal, plugin-candidate

#461 Add 'cropSymmetric' to AutoCrop
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/plugin-crop/README.md
  packages/plugin-crop/src/index.js
  packages/plugin-crop/test/autocrop.test.js
Labels: enhancement

#399 Add `leaveBorder` to AutoCrop
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/plugin-crop/src/index.js
  packages/plugin-crop/test/autocrop.test.js
Labels: enhancement

#596 Fisheye Plugin
  README.md
  packages/plugin-circle/test.png
  packages/plugin-fisheye/LICENSE
  packages/plugin-fisheye/README.md
  packages/plugin-fisheye/babel.config.js
  packages/plugin-fisheye/package.json
  packages/plugin-fisheye/src/index.js
  packages/plugin-fisheye/test/fisheye.js
Labels: internal, plugin-candidate

#599 shadow plugin
  README.md
  packages/plugin-shadow/LICENSE
  packages/plugin-shadow/README.md
  packages/plugin-shadow/babel.config.js
  packages/plugin-shadow/package.json
  packages/plugin-shadow/src/index.js
  packages/plugin-shadow/test/images/shadow.png
  packages/plugin-shadow/test/shadow.js
Labels: internal

#604 Png options
  packages/jimp/jimp.d.ts
  packages/type-png/README.md
  packages/type-png/src/index.js
  packages/type-png/test/images/options.png
  packages/type-png/test/png.test.js
Labels: bug

#608 remove link from all docs
  README.md
  packages/core/README.md
  packages/custom/README.md
  packages/jimp/README.md
  packages/plugin-blit/README.md
  packages/plugin-blur/README.md
  packages/plugin-circle/README.md
  packages/plugin-color/README.md
  packages/plugin-contain/README.md
  packages/plugin-cover/README.md
  packages/plugin-crop/README.md
  packages/plugin-displace/README.md
  packages/plugin-dither/README.md
  packages/plugin-fisheye/README.md
  packages/plugin-flip/README.md
  packages/plugin-gaussian/README.md
  packages/plugin-invert/README.md
  packages/plugin-mask/README.md
  packages/plugin-normalize/README.md
  packages/plugin-print/README.md
  packages/plugin-resize/README.md
  packages/plugin-rotate/README.md
  packages/plugin-scale/README.md
  packages/plugin-shadow/README.md
  packages/plugin-threshold/README.md
  packages/plugins/README.md
  packages/test-utils/README.md
  packages/type-bmp/README.md
  packages/type-gif/README.md
  packages/type-jpeg/README.md
  packages/type-png/README.md
  packages/type-tiff/README.md
  packages/types/README.md
  packages/utils/README.md
Labels: internal

#615 Licenses
  .vscode/launch.json
  packages/core/LICENSE
  packages/custom/LICENSE
  packages/jimp/LICENSE
  packages/jimp/test/images/exif-orientation/LICENSE
  packages/plugin-blit/LICENSE
  packages/plugin-blur/LICENSE
  packages/plugin-circle/LICENSE
  packages/plugin-color/LICENSE
  packages/plugin-contain/LICENSE
  packages/plugin-cover/LICENSE
  packages/plugin-crop/LICENSE
  packages/plugin-displace/LICENSE
  packages/plugin-dither/LICENSE
  packages/plugin-fisheye/LICENSE
  packages/plugin-flip/LICENSE
  packages/plugin-gaussian/LICENSE
  packages/plugin-invert/LICENSE
  packages/plugin-mask/LICENSE
  packages/plugin-normalize/LICENSE
  packages/plugin-print/LICENSE
  packages/plugin-resize/LICENSE
  packages/plugin-rotate/LICENSE
  packages/plugin-scale/LICENSE
  packages/plugin-shadow/LICENSE
  packages/plugin-threshold/LICENSE
  packages/plugins/LICENSE
  packages/test-utils/LICENSE
  packages/type-bmp/LICENSE
  packages/type-gif/LICENSE
  packages/type-jpeg/LICENSE
  packages/type-png/LICENSE
  packages/type-tiff/LICENSE
  packages/types/LICENSE
  packages/utils/LICENSE
Labels: internal

#613 Blit src params Issue
  packages/plugin-blit/src/index.js
  packages/plugin-blit/test/blit.test.js
  packages/plugin-blit/test/images/cat-results/large-cat.png
  packages/plugin-blit/test/images/cat-results/medium-cat.png
  packages/plugin-blit/test/images/cat-results/small-cat.png
  packages/plugin-blit/test/images/cat_butt.png
  packages/plugin-blit/test/images/cat_fuzz.png
  packages/plugin-blit/test/images/cat_head.png
Labels: bug

#616 Print Perf Enhancement
  packages/plugin-print/package.json
  packages/plugin-print/src/index.js
  packages/plugin-print/test/images/SANS_16_BLACK-positioned.png
  packages/plugin-print/test/images/print-number.png
  packages/plugin-print/test/images/unknown-char-test.png
  packages/plugin-print/test/print.test.js
Labels: bug

#606 @jimp/cli
  README.md
  package.json
  packages/cli/README.md
  packages/cli/babel.config.js
  packages/cli/package.json
  packages/cli/src/cli.ts
  packages/cli/src/index.ts
  packages/cli/src/load-font.ts
  packages/cli/src/log.ts
  packages/cli/src/process-image.ts
  packages/cli/test/cli.test.ts
  packages/cli/test/images/action-1.png
  packages/cli/test/images/action-2.png
  packages/cli/test/images/action-boolean.png
  packages/cli/test/images/action-print.png
  packages/cli/test/images/blit.png
  packages/cli/test/images/create-blank.png
  packages/cli/test/images/create.png
  packages/cli/test/images/qr-convoluted.png
  packages/cli/test/images/qr.jpg
  packages/cli/test/images/tiny-qr.png
  packages/cli/test/index.test.ts
  packages/cli/test/load-font.test.ts
  packages/cli/test/log.test.ts
  packages/cli/test/process-image.test.ts
  packages/cli/test/utils/makePath.ts
  packages/cli/test/utils/mock-console.ts
  packages/cli/tsconfig.json
  packages/custom/README.md
  packages/jimp/jimp.d.ts
  packages/plugin-print/test/print.test.js
  tsconfig.json
  yarn.lock
Labels: internal

#622 Color Perf Gains
  packages/cli/package.json
  packages/cli/test/cli.test.ts
  packages/cli/test/images/action-print.png
  packages/plugin-color/src/index.js
  packages/plugin-print/test/print.test.js
  yarn.lock
Labels: bug

#624 correct getBase64Async type def
  packages/jimp/jimp.d.ts
Labels: bug

#628 Expose ParseBitmap
  packages/core/src/index.js
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/plugin-color/src/index.js
  packages/plugin-print/test/print.test.js
  packages/type-png/test/png.test.js
Labels: bug

#629 add new constructor option to load url with options
  packages/core/src/index.js
  packages/core/src/request.js
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
Labels: enhancement

#630 update deps
  package.json
  packages/core/src/index.js
  packages/core/src/request.js
  packages/core/src/utils/image-bitmap.js
  packages/jimp/examples/example-greyscale.js
  packages/plugin-color/src/index.js
  packages/test-utils/src/jgd-wrapper.js
  yarn.lock
Labels: bug
