Repository jimp-dev/jimp, pull requests merged in 2018-08, with the labels that each got.

#403 Write using saved mime type
  README.md
  src/index.js
  test/filetypes.test.js
Labels: minor

#511 clean up getJimpDir
  src/constants.js
Labels: patch

#510 Errors
  src/index.js
  src/modules/resize2.js
  src/utils/image-bitmap.js
Labels: patch

#517 correct paths for fonts
  package.json
Labels: bug, patch

#514 allow constructor to use rgb data. support decoding outside of jimp
  README.md
  jimp.d.ts
  src/index.js
  test/filetypes.test.js
Labels: minor

#348 Rewrite the type declarations file
  jimp.d.ts
Labels: patch

#530 BMP Color issue
  src/index.js
  src/utils/abgr.js
  src/utils/image-bitmap.js
  src/utils/scan.js
  test/filetypes.test.js
  test/hash.test.js
  test/samples/windows95.png
Labels: patch

#529 polyfill es6 and es7 features for older versions of node
  .babelrc.js
Labels: patch

#515 Blendmodes
  .babelrc.js
  README.md
  jimp.d.ts
  src/constants.js
  src/image-manipulation/composite-modes.js
  src/image-manipulation/effects.js
  test/composite.test.js
  test/filetypes.test.js
  test/samples/cops-masked.jpg
Labels: minor

#534 Always return this for chaining
  jimp.d.ts
  src/image-manipulation/color.js
  src/image-manipulation/effects.js
  src/image-manipulation/shape.js
  src/image-manipulation/text.js
  src/index.js
  src/utils/error-checking.js
  src/utils/image-bitmap.js
  test/composite.test.js
Labels: patch

#533 ES6 tests
  test/async.test.js
  test/autocrop.test.js
  test/blit.test.js
  test/callbacks.test.js
  test/color.test.js
  test/colordiff.test.js
  test/compare.test.js
  test/convolution.test.js
  test/cover-and-contain.test.js
  test/events.test.js
  test/exif.test.js
  test/filetypes.test.js
  test/hash.test.js
  test/jgd-wrapper.js
  test/jgd.test.js
  test/mask.test.js
  test/mime.test.js
  test/normalize.test.js
  test/pixelate.js
  test/print.test.js
  test/promise.test.js
  test/resize.test.js
  test/rotation.test.js
  test/scan.test.js
  test/test-helper.js
Labels: patch

#535 fix types
  jimp.d.ts
Labels: patch

#539 Broken tests
  src/utils/error-checking.js
Labels: patch

#541 comparing buffers takes a long time so increase the timeout for test:browser
  test/filetypes.test.js
Labels: patch

#544 Include babel/polyfill
  package.json
  src/utils/image-bitmap.js
  yarn.lock
Labels: patch

#551 update load-bmfont
  package.json
  yarn.lock
Labels: patch

#553 Audit Deps
  package.json
  yarn.lock
Labels: patch

#550 Printing unknown white space char
  src/image-manipulation/text.js
Labels: patch

#555 Text Function Simplification
  README.md
  jimp.d.ts
  src/constants.js
  src/image-manipulation/text.js
  src/index.js
  src/utils/measure-text.js
  test/print.test.js
  test/samples/text-samples/SANS_64_BLACK.png
  test/samples/text-samples/SANS_64_WHITE.png
  test/samples/text-samples/bottom-aligned.png
  test/samples/text-samples/center-aligned.png
  test/samples/text-samples/left-aligned.png
  test/samples/text-samples/middle-aligned.png
  test/samples/text-samples/right-aligned.png
Labels: patch

#563 get first letter rather than '0'. cause '0' might no be present
  src/image-manipulation/text.js
  src/index.js
Labels: patch

#566 Build stuff
  package.json
  packages/core/package.json
  packages/core/test/utils/mime.test.js
  packages/custom/package.json
  packages/jimp/jimp.d.ts
  packages/jimp/package.json
  packages/plugin-blit/package.json
  packages/plugin-blur/package.json
  packages/plugin-color/package.json
  packages/plugin-contain/package.json
  packages/plugin-contain/src/index.js
  packages/plugin-cover/package.json
  packages/plugin-crop/package.json
  packages/plugin-displace/package.json
  packages/plugin-displace/src/index.js
  packages/plugin-dither/package.json
  packages/plugin-flip/package.json
  packages/plugin-flip/src/index.js
  packages/plugin-gaussian/package.json
  packages/plugin-invert/package.json
  packages/plugin-mask/package.json
  packages/plugin-mask/src/index.js
  packages/plugin-normalize/package.json
  packages/plugin-normalize/src/index.js
  packages/plugin-print/package.json
  packages/plugin-resize/package.json
  packages/plugin-rotate/package.json
  packages/plugin-scale/package.json
  packages/plugin-scale/src/index.js
  packages/type-bmp/package.json
  packages/type-bmp/src/index.js
  packages/type-gif/package.json
  packages/type-gif/src/index.js
  packages/type-jpeg/package.json
  packages/type-jpeg/src/index.js
  packages/type-png/package.json
  packages/type-png/src/index.js
  packages/type-tiff/package.json
  packages/type-tiff/src/index.js
  packages/utils/package.json
Labels: patch

#567 Fix raw buffer constructor example
  README.md
Labels: patch

#573 Update Readmes
  README.md
  packages/core/README.md
  packages/custom/README.md
  packages/jimp/README.md
  packages/plugin-blit/README.md
  packages/plugin-blur/README.md
  packages/plugin-blur/src/index.js
  packages/plugin-color/README.md
  packages/plugin-contain/README.md
  packages/plugin-cover/README.md
  packages/plugin-crop/README.md
  packages/plugin-displace/README.md
  packages/plugin-dither/README.md
  packages/plugin-flip/README.md
  packages/plugin-gaussian/README.md
  packages/plugin-invert/README.md
  packages/plugin-mask/README.md
  packages/plugin-normalize/README.md
  packages/plugin-print/README.md
  packages/plugin-resize/README.md
  packages/plugin-rotate/README.md
  packages/plugin-scale/README.md
  packages/plugins/README.md
  packages/type-bmp/README.md
  packages/type-gif/README.md
  packages/type-jpeg/README.md
  packages/type-png/README.md
  packages/type-tiff/README.md
  packages/types/README.md
  packages/utils/README.md
Labels: internal

#576 Core-js conflict
  packages/jimp/package.json
Labels: bug

#579 babel 7 :tada:
  package.json
  packages/jimp/package.json
  yarn.lock
Labels: internal

#582 TSC change to default export
  packages/jimp/jimp.d.ts
Labels: bug
