Repository jimp-dev/jimp, pull requests merged in 2019-11, with the labels that each got.

#820 Revert exports to match 0.6.4 TS definitions
  packages/jimp/types/index.d.ts
  packages/jimp/types/test.ts
  packages/jimp/types/ts3.1/index.d.ts
  packages/jimp/types/ts3.1/test.ts
Labels: minor

#810 Added callback to jimp constructor typings
  packages/core/types/jimp.d.ts
  packages/jimp/types/index.d.ts
  packages/jimp/types/test.ts
  packages/jimp/types/ts3.1/test.ts
Labels: patch

#789 Follow redirects
  packages/core/src/index.js
  packages/core/test/images/pixel.png
  packages/core/test/redirect.test.js
Labels: patch

#824 update auto
  CHANGELOG.md
  package.json
  yarn.lock
Labels: internal, skip-release
