Repository jimp-dev/jimp, pull requests merged in 2019-09, with the labels that each got.

#784 Add Automated Releases
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  RELEASING.md
  package.json
  yarn.lock
Labels: internal

#741 Fix cropping full width slices
  packages/plugin-crop/src/index.js
  packages/plugin-crop/test/crop.test.js
Labels: patch

#743 Plugin crop/fix safety checks
  packages/plugin-crop/src/index.js
  packages/plugin-crop/test/autocrop.test.js
Labels: patch

#783 Remove dependency '@babel/polyfill' and add 'regenerator-runtime'
  packages/jimp/package.json
  yarn.lock
Labels: patch

#781 Feature scanIterator
  packages/core/src/index.js
  packages/jimp/README.md
  packages/jimp/jimp.d.ts
  packages/jimp/test/scan.test.js
  packages/utils/README.md
  packages/utils/src/index.js
Labels: minor

#786 Fix 0.8 typings, add type tests
  .circleci/config.yml
  package.json
  packages/cli/src/load-font.ts
  packages/core/index.d.ts
  packages/core/package.json
  packages/core/types/etc.d.ts
  packages/core/types/functions.d.ts
  packages/core/types/index.d.ts
  packages/core/types/jimp.d.ts
  packages/core/types/plugins.d.ts
  packages/core/types/utils.d.ts
  packages/custom/index.d.ts
  packages/custom/package.json
  packages/custom/types/index.d.ts
  packages/custom/types/test.ts
  packages/custom/types/tsconfig.json
  packages/jimp/index.d.ts
  packages/jimp/package.json
  packages/jimp/types/index.d.ts
  packages/jimp/types/test.ts
  packages/jimp/types/ts3.1/index.d.ts
  packages/jimp/types/ts3.1/test.ts
  packages/jimp/types/ts3.1/tsconfig.json
  packages/jimp/types/tsconfig.json
  packages/plugin-blit/index.d.ts
  packages/plugin-blur/index.d.ts
  packages/plugin-color/index.d.ts
  packages/plugin-contain/index.d.ts
  packages/plugin-cover/index.d.ts
  packages/plugin-displace/index.d.ts
  packages/plugin-dither/index.d.ts
  packages/plugin-flip/index.d.ts
  packages/plugin-gaussian/index.d.ts
  packages/plugin-invert/index.d.ts
  packages/plugin-mask/index.d.ts
  packages/plugin-normalize/index.d.ts
  packages/plugin-rotate/index.d.ts
  packages/plugin-scale/index.d.ts
  packages/plugin-threshold/package.json
  packages/plugins/index.d.ts
  packages/utils/index.d.ts
  yarn.lock
Labels: patch

#794 must ship types
  packages/jimp/package.json
Labels: patch

#798 TS 3.1 fixed
  packages/cli/package.json
  packages/core/types/etc.d.ts
  packages/core/types/jimp.d.ts
  packages/core/types/utils.d.ts
  packages/custom/types/test.ts
  packages/jimp/package.json
  packages/jimp/types/index.d.ts
  packages/jimp/types/test.ts
  packages/jimp/types/ts3.1/index.d.ts
  packages/jimp/types/ts3.1/test.ts
  packages/plugin-blit/index.d.ts
  packages/plugin-blur/index.d.ts
  packages/plugin-circle/index.d.ts
  packages/plugin-color/index.d.ts
  packages/plugin-contain/index.d.ts
  packages/plugin-cover/index.d.ts
  packages/plugin-crop/index.d.ts
  packages/plugin-displace/index.d.ts
  packages/plugin-dither/index.d.ts
  packages/plugin-fisheye/index.d.ts
  packages/plugin-flip/index.d.ts
  packages/plugin-gaussian/index.d.ts
  packages/plugin-invert/index.d.ts
  packages/plugin-mask/index.d.ts
  packages/plugin-normalize/index.d.ts
  packages/plugin-print/index.d.ts
  packages/plugin-resize/index.d.ts
  packages/plugin-rotate/index.d.ts
  packages/plugin-scale/index.d.ts
  packages/plugin-shadow/index.d.ts
  packages/plugin-threshold/index.d.ts
  packages/type-jpeg/index.d.ts
  packages/type-png/index.d.ts
  yarn.lock
Labels: patch

#800 Added back mention of required tsconfig options
  packages/jimp/README.md
Labels: documentation, skip-release

#799 Upgrade nearly-all dev deps
  .circleci/config.yml
  package.json
  packages/cli/package.json
  packages/core/src/index.js
  packages/core/src/modules/phash.js
  packages/jimp/package.json
  packages/jimp/test/callbacks.test.js
  packages/jimp/test/filetypes.test.js
  packages/jimp/test/hash.test.js
  packages/jimp/tools/browser-build.js
  packages/plugin-blit/test/blit.test.js
  packages/plugin-blur/src/index.js
  packages/plugin-color/src/index.js
  packages/plugin-crop/src/index.js
  packages/plugin-normalize/src/index.js
  packages/plugin-resize/src/modules/resize.js
  packages/plugin-resize/src/modules/resize2.js
  packages/plugin-resize/test/resize.test.js
  packages/plugin-rotate/src/index.js
  packages/test-utils/src/index.js
  packages/test-utils/src/jgd.js
  packages/type-jpeg/test/jpeg.test.js
  packages/type-png/test/png.test.js
  packages/type-tiff/test/tiff.test.js
  packages/types/package.json
  yarn.lock
Labels: internal, skip-release
