Repository jimp-dev/jimp, pull requests merged in 2020-03, with the labels that each got.

#841 Update plugin-shadow type definition.
  packages/plugin-shadow/index.d.ts
Labels: patch

#845 Added ttf2fnt.com to the list
  packages/plugin-print/README.md
Labels: documentation

#838 Export font type
  packages/plugin-print/index.d.ts
Labels: patch

#858 Fix TypeScript error on 'next'
  packages/core/types/jimp.d.ts
  packages/core/types/utils.d.ts
  packages/custom/types/test.ts
  packages/jimp/types/index.d.ts
  packages/jimp/types/test.ts
Labels: internal, skip-release

#857 Relax mkdirp dependency to allow newer minimist
  packages/core/package.json
Labels: patch

#860 upgrade auto
  .circleci/config.yml
  package.json
  packages/jimp/package.json
  yarn.lock
Labels: patch

#859 Relax version range of plugin-threshold peerDependencies
  packages/plugin-threshold/package.json
Labels: patch

#863 Added missing plugins to the types
  packages/jimp/types/test.ts
  packages/jimp/types/ts3.1/test.ts
  packages/plugins/index.d.ts
Labels: patch

#867 Properly split constructor and instance types
  packages/core/types/jimp.d.ts
  packages/core/types/utils.d.ts
  packages/custom/types/index.d.ts
  packages/custom/types/test.ts
  packages/jimp/types/ts3.1/index.d.ts
  packages/jimp/types/ts3.1/test.ts
  packages/type-jpeg/index.d.ts
Labels: minor
