Repository jimp-dev/jimp, pull requests merged in 2023-02, with the labels that each got.

#992 it's -> its ;)
  README.md
Labels: documentation

#1127 only build node 16
  .circleci/config.yml
  .github/actions/build-cache/action.yml
  .github/actions/install-deps/action.yml
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: internal

#1131 update jpeg-js
  packages/type-jpeg/package.json
  yarn.lock
Labels: minor

#1149 Babel Refactor
  .browserslistrc
  babel.config.js
  package.json
  packages/core/package.json
  packages/custom/package.json
  packages/jimp/package.json
  packages/jimp/test/scan.test.js
  packages/jimp/webpack.config.ts
  packages/plugin-blit/package.json
  packages/plugin-blur/package.json
  packages/plugin-circle/package.json
  packages/plugin-color/package.json
  packages/plugin-contain/package.json
  packages/plugin-cover/package.json
  packages/plugin-crop/package.json
  packages/plugin-displace/package.json
  packages/plugin-dither/package.json
  packages/plugin-fisheye/package.json
  packages/plugin-flip/package.json
  packages/plugin-gaussian/package.json
  packages/plugin-invert/package.json
  packages/plugin-mask/package.json
  packages/plugin-normalize/package.json
  packages/plugin-print/package.json
  packages/plugin-resize/package.json
  packages/plugin-rotate/package.json
  packages/plugin-scale/package.json
  packages/plugin-shadow/package.json
  packages/plugin-threshold/package.json
  packages/plugins/package.json
  packages/test-utils/package.json
  packages/type-bmp/package.json
  packages/type-gif/package.json
  packages/type-jpeg/package.json
  packages/type-png/package.json
  packages/type-tiff/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: major

#1161 Change test matching strategy to include all test files
  packages/core/package.json
  packages/jimp/package.json
  packages/plugin-blit/package.json
  packages/plugin-circle/package.json
  packages/plugin-color/package.json
  packages/plugin-contain/package.json
  packages/plugin-cover/package.json
  packages/plugin-crop/package.json
  packages/plugin-fisheye/package.json
  packages/plugin-flip/package.json
  packages/plugin-mask/package.json
  packages/plugin-normalize/package.json
  packages/plugin-print/package.json
  packages/plugin-resize/package.json
  packages/plugin-rotate/package.json
  packages/plugin-shadow/package.json
  packages/plugin-threshold/package.json
  packages/test-utils/package.json
  packages/type-bmp/package.json
  packages/type-gif/babel.config.js
  packages/type-gif/package.json
  packages/type-jpeg/package.json
  packages/type-png/package.json
  packages/type-tiff/package.json
Labels: internal

#1162 delete CLI package
  CHANGELOG.md
  packages/cli/CHANGELOG.md
  packages/cli/README.md
  packages/cli/babel.config.js
  packages/cli/package.json
  packages/cli/src/cli.ts
  packages/cli/src/index.ts
  packages/cli/src/load-font.ts
  packages/cli/src/log.ts
  packages/cli/src/process-image.ts
  packages/cli/test/cli.test.ts
  packages/cli/test/images/action-1.png
  packages/cli/test/images/action-2.png
  packages/cli/test/images/action-boolean.png
  packages/cli/test/images/action-print.png
  packages/cli/test/images/blit.png
  packages/cli/test/images/create-blank.png
  packages/cli/test/images/create.png
  packages/cli/test/images/qr-convoluted.png
  packages/cli/test/images/qr.jpg
  packages/cli/test/images/tiny-qr.png
  packages/cli/test/index.test.ts
  packages/cli/test/load-font.test.ts
  packages/cli/test/log.test.ts
  packages/cli/test/process-image.test.ts
  packages/cli/test/utils/makePath.ts
  packages/cli/test/utils/mock-console.ts
  packages/cli/tsconfig.json
  packages/core/CHANGELOG.md
  packages/plugin-resize/CHANGELOG.md
Labels: internal

#1163 switch from should to expect
  package.json
  packages/core/package.json
  packages/core/test/utils/mime.test.js
  packages/custom/types/tsconfig.json
  packages/jimp/test/async.test.js
  packages/jimp/test/callbacks.test.js
  packages/jimp/test/colordiff.test.js
  packages/jimp/test/composite.test.js
  packages/jimp/test/diff.test.js
  packages/jimp/test/events.test.js
  packages/jimp/test/exif-rotation.test.js
  packages/jimp/test/filetypes.test.js
  packages/jimp/test/hash.test.js
  packages/jimp/test/scan.test.js
  packages/jimp/types/tsconfig.json
  packages/plugin-blit/test/blit.test.js
  packages/plugin-circle/test/circle.test.js
  packages/plugin-color/test/color.test.js
  packages/plugin-color/test/convolution.test.js
  packages/plugin-contain/test/contain.test.js
  packages/plugin-cover/test/cover.test.js
  packages/plugin-crop/test/autocrop.test.js
  packages/plugin-crop/test/crop.test.js
  packages/plugin-fisheye/test/fisheye.test.js
  packages/plugin-flip/test/flipping.test.js
  packages/plugin-mask/test/mask.test.js
  packages/plugin-normalize/test/normalize.test.js
  packages/plugin-print/test/print.test.js
  packages/plugin-resize/test/resize.test.js
  packages/plugin-rotate/test/rotation.test.js
  packages/plugin-shadow/test/shadow.test.js
  packages/plugin-threshold/test/threshold.test.js
  packages/test-utils/package.json
  packages/test-utils/src/index.js
  packages/test-utils/test/jgd.test.js
  packages/type-bmp/test/bmp.test.js
  packages/type-gif/test/gif.test.js
  packages/type-jpeg/test/jpeg.test.js
  packages/type-png/test/png.test.js
  packages/type-tiff/test/tiff.test.js
  yarn.lock
Labels: internal

#1169 rename master to main
  .github/workflows/build.yml
  CHANGELOG.md
  packages/core/CHANGELOG.md
  packages/custom/CHANGELOG.md
  packages/jimp/CHANGELOG.md
  packages/plugin-blit/CHANGELOG.md
  packages/plugin-blur/CHANGELOG.md
  packages/plugin-circle/CHANGELOG.md
  packages/plugin-color/CHANGELOG.md
  packages/plugin-contain/CHANGELOG.md
  packages/plugin-cover/CHANGELOG.md
  packages/plugin-crop/CHANGELOG.md
  packages/plugin-displace/CHANGELOG.md
  packages/plugin-dither/CHANGELOG.md
  packages/plugin-fisheye/CHANGELOG.md
  packages/plugin-flip/CHANGELOG.md
  packages/plugin-gaussian/CHANGELOG.md
  packages/plugin-invert/CHANGELOG.md
  packages/plugin-mask/CHANGELOG.md
  packages/plugin-normalize/CHANGELOG.md
  packages/plugin-print/CHANGELOG.md
  packages/plugin-print/test/print.test.js
  packages/plugin-resize/CHANGELOG.md
  packages/plugin-rotate/CHANGELOG.md
  packages/plugin-scale/CHANGELOG.md
  packages/plugin-shadow/CHANGELOG.md
  packages/plugin-threshold/CHANGELOG.md
  packages/plugins/CHANGELOG.md
  packages/test-utils/CHANGELOG.md
  packages/type-bmp/CHANGELOG.md
  packages/type-gif/CHANGELOG.md
  packages/type-jpeg/CHANGELOG.md
  packages/type-png/CHANGELOG.md
  packages/type-tiff/CHANGELOG.md
  packages/types/CHANGELOG.md
  packages/utils/CHANGELOG.md
Labels: internal

#1172 Windows scripts
  package.json
  yarn.lock
Labels: internal

#1176 Remove mentioning of `favicons`
  README.md
Labels: documentation

#1203 Update README.md
  README.md
Labels: documentation

#1202 Fix resizing issue with Jimp.AUTO
  packages/plugin-resize/src/index.js
Labels: patch

#1205 Export ColorActionName enum
  packages/jimp/types/test.ts
  packages/plugin-color/index.d.ts
  packages/plugin-color/src/index.js
Labels: patch

#1209 use matrix rotate, if rotate angle is multiple of 90 degrees
  packages/plugin-rotate/src/index.js
  packages/plugin-rotate/test/rotation.test.js
Labels: patch
